spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mutants_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    schemas: mutants_db
    enabled: false