spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mutants_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
  flyway:
    schemas: mutants_db
    enabled: true
  security:
    user:
      name: mutant
      password: mutantPass
mutant:
  min-sequence-length: 4